### ISSUE TITLE
Couple of potential bugs - Object render disabled and Text objects with numbers

### ISSUE THREAD

**Issue by bevels** [torrinworx/Blend_My_NFTs#61]
I'm using Blender 3.0.1 and the latest release of BMNFTs (downloaded 22/02/22)

In 'Create NFT Data', when I hit 'Create Data', it works as intended, however it disables render on random objects. I say random, because if I run the process twice, different objects get disabled. If I go ahead and click the 'generate nfts' button, those layers won't render. It's not a show stopper, I just turn render on again for those objects that have been disabled before generating the NFT's.

Second issue I've encountered, which is a bit odd. If I have text objects in my scene with numbers (not in the object title, in the actual scene), it won't render that object. In my case these text objects have numbers, a minus symbol and full stops. If I convert the text object to a mesh, problem solved.

Hope that helps squish a couple of buggies. Thanks for the epic addon!!!

**Comment by torrinworx** [comment]
Problem 1 is an issue with the Colour and material generator. This feature was turned off, but remnants of the code are still in the DNA_Generator.py and other files. This will be solved when the material generator is re-created in a future update. 

This might be because the text object's name is being recognized as a collection by BMNFTs. Not really sure what the best workaround is for this. Ask Devlin in our Discord server, he may have better insight into this issue. 

Thanks for the bug report!
