### ISSUE TITLE
Only With Rule in Logic.py doesn't work

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/Blend_My_NFTs#66]

**Comment by ethangale25** [comment]
Hey!

I was just considering using the Logic.json file to create some rules because I am running into a few conditions I'd like to meet when rendering...

If you could please include some examples in the README.md file of how both the "Never With" and "Only With" Logic is used in scenarios in both referencing whole attributes and single variants?

I don't know if this is how the logic is intended to work but..
 
Example:
{
    "Rule-1":{
        "Items-1": [
            "Silver Body_1_75"
        ],
        "Rule": "Never with", 
        "Items-2":[
            "Silver Arms_1_75"
        ]
    },
}

This would mean that a silver body would never appear with a silver arm. Furthermore, In the case where the randomly generated NFT randomly selects both the Silver Body_1_75 collection and the Silver Arms_1_75 collection, no arms would be rendered in the final NFT because:

1. The Silver Body_1_75 collection and the Silver Arms_1_75 collection cannot be paired due to the "Never with" logic and...
2. No other arm variant will be selected after the logic notices Silver Arms_1_75 cannot be paired with Silver Body_1_75

Thanks for all your hard work on this project. It can and will change peoples lives for the better! Cheers mate!

**Comment by torrinworx** [comment]
Fixed as of the Logic-Patch, BMNFTs v2.1.0. I will add more documentation to the readme file about how to use Logic and the new custom metadata fields sometime this weekend 👍
