### ISSUE TITLE
Usage in 2.83 or 2.79 on MacOS

### ISSUE THREAD

**Issue by Justiniscoding** [torrinworx/Blend_My_NFTs#74]
I am using blender version 2.79, and cannot upgrade it due to my OS. Whenever I try running it, it gives me an error. Here is a screenshot (It would not let me copy and paste)
![Screen Shot 2022-03-23 at 7 29 24 PM](https://user-images.githubusercontent.com/76059890/159813195-240ef4a5-c0a1-4f9a-a988-28fec76ccd89.png)
Is there a patch I can apply to the code to make it work for my version? (I don't use python or bpy)

**Comment by torrinworx** [comment]
Hi @Justiniscoding, Blend_My_NFTs only supports 3.0 because it uses some relatively new features of the UI system. 

You could try removing the following lines of code from the [__init__.py](https://github.com/torrinworx/Blend_My_NFTs/blob/main/__init__.py) file in Blend_My_NFTs:

<img width="754" alt="Screen Shot 2022-03-25 at 7 51 37 AM" src="https://user-images.githubusercontent.com/82110564/160115870-378781c6-47ba-48d7-aa37-49127f01ac55.png">

<img width="642" alt="Screen Shot 2022-03-25 at 7 53 08 AM" src="https://user-images.githubusercontent.com/82110564/160116073-3d27d6bc-3a22-4bee-936a-512271fb544d.png">

**Comment by torrinworx** [comment]
That should get rid of the error message that you are seeing, but I couldn't tell you if there are going to be more.

**Comment by Justiniscoding** [comment]
It did install and gave a warning that it might not function properly, and I will be trying to use the plugin now

**Comment by Justiniscoding** [comment]
Blender 2.79 does not have the feature to create collections. However, it turns out I can upgrade to v2.8.3 which introduced the feature.

**Comment by Justiniscoding** [comment]
The plugin does not work when I try to click create data. I get the following error:
![Screen Shot 2022-03-25 at 10 27 28 AM](https://user-images.githubusercontent.com/76059890/160140289-1154309b-34e2-4cb5-a2fc-9fab1ee8313f.png)

**Comment by torrinworx** [comment]
Closing for now, feel free to re-open if you are still having issues.

**Comment by Justiniscoding** [comment]
I am still having issues, I cannot generate the NFT's or create the data because I get an error message

> @torrinworx The plugin does not work when I try to click create data. I get the following error: ![Screen Shot 2022-03-25 at 10 27 28 AM](https://user-images.githubusercontent.com/76059890/160140289-1154309b-34e2-4cb5-a2fc-9fab1ee8313f.png)

**Comment by Justiniscoding** [comment]
> Also, I was able to install the plugin without modifying the `__init__.py` file when using 2.83

@torrinworx  I realize I wasn't clear enough when I said this. I meant to say that the starting works fine with 2.83 but when I try to generate the data I get the error mentioned above. Also, I can't reopen the issue
